### ISSUE TITLE
2 small assembly instruction bugs in op-riscv.c

### ISSUE THREAD

**Issue by HAM41** [physical-computation/sunflower-simulator#104]
There appear to be two small bugs in op-riscv which I have thought to correct in a certain way. My suggested correction for  Bug 1 is included in my pull request for issue-100 which will be merged in soon, but my suggested correction to Bug 2 is not included anywhere. These may in fact not be bugs, hence I have made the issue to check.

### Bug 1

In the rv32f_fcvt_w_s and rv32f_fcvt_wu_s functions the result was being written to a floating point register. However, these instructions should be writing to a normal register (non-floating point)<sup>1</sup>, so I changed the line "freg_set_riscv(E, S, rd, nan_box(result));" to "reg_set_riscv(E, S, rd, nan_box(result));" to correct this.

### Bug 2

The bottom most assembly instruction in op-riscv.c is rv32f_fcvt_d_wu. This is an RV32D or RV64D instruction, as if the instruction one above this (rv32d_fcvt_d_w), so I believe that the bottom most assembly instruction should be renamed to: rv32d_fcvt_d_wu (a 'd' instead of an 'f' before the first underscore), as this instruction deals with a double precision float. Note that changing this would require changing the name of that instruction in two other places (in different files) in Sunflower. 

<sup>1</sup>: The RISC-V Reader An Open Architecture Atlas, version 1.0.0 (7 November 2017) by David Patterson and Andrew Waterman

**Comment by harrysarson** [comment]
### Bug 1

That looks like a bug to me! For the fix `freg_set_riscv(E, S, rd, nan_box(result))` should be changed to `reg_set_riscv(E, S, rd, result)` (we do not want to nan box).

### Bug 2

Also looks like a bug! The fix sounds good.

🙂

**Comment by phillipstanleymarbell** [comment]
@harrysarson, could you verify the fix (now merged into master).

**Comment by HAM41** [comment]
@harrysarson  I assume from your comment on the pull request that has now been merged that this issue can be closed?

**Comment by harrysarson** [comment]
Yes, let's close! (Fixed in #102)
