### ISSUE TITLE
Instruction Distribution incrementing in riscvstep in pipeline-riscv.c

### ISSUE THREAD

**Issue by HAM41** [physical-computation/sunflower-simulator#105]
This may be a legacy problem caused by the fact that the riscv pipeline was changed, but the instruction_distribution array was only incrementing in the riscvfaststep function, whilst it should also have been incrementing in the riscvstep function in the file riscv-pipeline.c . In my pull request (Implementation of taint analysis (not yet working though)) I have implemented an increment for instruction_distribution in the riscvstep function as well, upon the instruction of Samuel Wong.

**Comment by phillipstanleymarbell** [comment]
The RISC-V pipeline wasn't changed: it didn't exist before @SamuelmsWong implemented the pipelining. Assign to @SamuelmsWong and have his review the changes you made to his implementation.
