### ISSUE TITLE
Adding in start and end PC values and other features

### ISSUE THREAD

**Issue by HAM41** [physical-computation/sunflower-simulator#106]
The dumptaintdistr now outputs the taint of each command in binary. Can now specify a range of PC values when a register should act as a taint origin. Have also added my name at the top of relevant files.

Potentially wait with merging this in, in case someone else requests other changes to taint analysis over the next two days.

**Comment by phillipstanleymarbell** [comment]
Did you intend to create an issue or a pull request?

**Comment by HAM41** [comment]
Pull request. I thought, as the previous one was closed I should create a new one (am about to actually send the pull request)
