### ISSUE TITLE
Examples in sbench directory fail to compile

### ISSUE THREAD

**Issue by JamesTimothyMeech** [physical-computation/sunflower-simulator#178]
When running sunflower on CPU1 (Linux) and compiling for the superH architecture 
all of the examples in the sbench directory fail to compile. 

Adding the line ```#include <stdint.h>``` to the file ```sf-types.h``` fixes the compilation issue.

Running any of the examples in sbench after this fix produces this message from sunflower: ```Exiting: Failed to allocate memory for S->MEM.
	Writing all node information to sunflower.out```

**To Reproduce**
1. make in any sbench benchmark
2. See error.

**Expected behavior**
Benchmarks should compile and run without errors.

**Screenshots**

**Host OS (please complete the following information):**
 - OS: Linux.

**You local changes (please complete the following information):**
 - Output of `git diff`:
```diff --git a/sim/sf-types.h b/sim/sf-types.h
index 3b9c51c..b5caf49 100755
--- a/sim/sf-types.h
+++ b/sim/sf-types.h
@@ -34,7 +34,7 @@
        ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
        POSSIBILITY OF SUCH DAMAGE.
 */
-
+#include <stdint.h>
 #define nil    ((void*)0)
 #define USED(x)
 #define uchar  uint8_t
diff --git a/sunflower-toolchain b/sunflower-toolchain
index 20c35a7..14a1e96 160000
--- a/sunflower-toolchain
+++ b/sunflower-toolchain
@@ -1 +1 @@
-Subproject commit 20c35a7caf51db8b080eeaa44d823295bba24e6e
+Subproject commit 14a1e96c111a326c348c7db80b1f9f7022630476-dirty```
- Output of `git remote -v`":
```origin	git@github.com:JamesTimothyMeech/sunflower-simulator.git (fetch)
origin	git@github.com:JamesTimothyMeech/sunflower-simulator.git (push)```

**Comment by phillipstanleymarbell** [comment]
I would be happy to merge a pull request.

**Comment by JamesTimothyMeech** [comment]
This was fixed here: https://github.com/physical-computation/sunflower-simulator/pull/179

Sorry, I forgot to close the issue.
