### ISSUE TITLE
`mkopstr-riscv` leads to a `opstr-riscv.h` with a duplicate entries on lines 40 and 41 in the `riscv_opstrs[]` array

### ISSUE THREAD

**Issue by phillipstanleymarbell** [physical-computation/sunflower-simulator#30]
`mkopstr-riscv` leads to a `opstr-riscv.h` with a duplicate entries on lines 40 and 41 in the `riscv_opstrs[]` array.

(cc: @Z-Gu)

**Comment by SamuelmsWong** [comment]
Problem is solved and merged; please close.
